//import all components here and export them
export {default as Browser_Bar} from './browser_bar'
export {default as Fake_Netflix} from './fake_netflix'
export {default as Level_Prototype} from './level_prototype'
export {default as UI_Overlay} from './ui_overlay'
export {default as Apple_music_email} from './apple_music_email'
export {default as Iphone_Text} from './iphone_text'
export {default as Amazon_Voicemail} from './amazon_voicemail'
export {default as Coupon} from './coupon'
export {default as Puppy_Site} from './puppy_site'
export {default as IRS_Email} from './irs_email'
export {default as Clickable_Region} from './clickable_region'
export {default as Target_Letter} from './target_letter'